version: '2'
services:
  web:
    container_name: vertxmon
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - db
    network_mode: host
  db:
    container_name: mongo
    image: mongo
    network_mode: host
